### ISSUE TITLE
Improve Navbar and add styling

### ISSUE THREAD

**Issue by SmrutiRanjan-L** [CareerDevelopmentHub/Attendance-Management-System#2]
add focus change and dark mode if possible

**Comment by Krest-Coder** [comment]
Sounds great.. You can do it.

**Comment by SmrutiRanjan-L** [comment]
![Screenshot (481)](https://user-images.githubusercontent.com/81686733/194722267-41e07acb-324e-42a8-825a-b402b9f3c57c.png)
![Screenshot (482)](https://user-images.githubusercontent.com/81686733/194722272-341339ab-051e-465d-9080-a97dc12dd7e2.png)

**Comment by Krest-Coder** [comment]
Great work.. It is as expected.
